# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"core_fn": "00_core.ipynb",
         "Apple": "00a_apple.ipynb",
         "core_text_fn": "10_text_core.ipynb",
         "text_util_fn": "10a_text_utils.ipynb"}

modules = ["core.py",
           "apple.py",
           "text/core.py",
           "text/utils.py"]

doc_url = "https://pete88b.github.io/nbdev_demo/"

git_url = "https://github.com/pete88b/nbdev_demo/tree/main/"

def custom_doc_links(name): return None
