# AUTOGENERATED! DO NOT EDIT! File to edit: 00a_apple.ipynb (unless otherwise specified).

__all__ = ['Apple']

# Cell
class Apple:
    "Represents an apple and things you can do with apples"
    def __init__(self,color,size,core):
        "Create a new apple with `color`, `size` and `core`"
    def bite(self):
        "Take a bite from the apple"