# AUTOGENERATED! DO NOT EDIT! File to edit: 10a_text_utils.ipynb (unless otherwise specified).

__all__ = ['text_util_fn']

# Cell
from .core import *

# Cell
def text_util_fn():
    "Adds some behaviour to `core_text_fn`"
    return core_text_fn()